import { VercelRequest, VercelResponse } from "@vercel/node";
import { execFileSync } from "child_process";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import Stripe from "stripe";

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, { apiVersion: "2023-10-16" });

interface GenerateRequest {
  api_url: string;
  api_name: string;
  cli_name?: string;
  payment_intent_id?: string;
  subscription_id?: string;
  include_mcp?: boolean;
  include_skill?: boolean;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const body = req.body as GenerateRequest;

  if (!body.api_url || !body.api_name) {
    return res.status(400).json({ error: "api_url and api_name required" });
  }

  // Verify payment
  const authorized = await verifyPayment(body.payment_intent_id, body.subscription_id);
  if (!authorized) {
    return res.status(402).json({ error: "Payment required", checkout_url: buildCheckoutUrl(body) });
  }

  // Generate the CLI
  try {
    const githubRepo = req.headers["x-github-repo"] as string | undefined;
    const result = await generateCLI(body, githubRepo);
    return res.status(200).json(result);
  } catch (err: any) {
    console.error("Generation failed:", err);
    return res.status(500).json({ error: "Generation failed", message: err.message });
  }
}

async function verifyPayment(intentId?: string, subscriptionId?: string): Promise<boolean> {
  if (subscriptionId) {
    const sub = await stripe.subscriptions.retrieve(subscriptionId);
    return sub.status === "active";
  }

  if (intentId) {
    const intent = await stripe.paymentIntents.retrieve(intentId);
    return intent.status === "succeeded";
  }

  return false;
}

async function generateCLI(body: GenerateRequest, githubRepo?: string) {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "ppaas-"));

  const cliName = body.cli_name || body.api_name.toLowerCase().replace(/\s+/g, "-");

  // Build args as an array — never join into a shell string to prevent injection
  const args = [
    "--api", body.api_url,
    "--name", cliName,
    "--output", tmpDir,
    "--lang", "go",
  ];

  if (body.include_mcp !== false) args.push("--mcp");
  if (body.include_skill !== false) args.push("--skill");

  // execFileSync spawns the binary directly; no shell, no injection risk
  execFileSync("printing-press", args, { timeout: 300_000, stdio: "pipe" });

  // Collect generated files
  const files: Record<string, string> = {};
  collectFiles(tmpDir, tmpDir, files);

  // Deliver via GitHub PR if token and repo header are present
  let github_pr_url: string | undefined;
  const githubToken = process.env.GITHUB_TOKEN;

  if (githubToken && githubRepo) {
    github_pr_url = await deliverViaGitHub(files, githubRepo, cliName, githubToken);
  }

  // Cleanup
  fs.rmSync(tmpDir, { recursive: true, force: true });

  return {
    success: true,
    cli_name: body.cli_name || body.api_name.toLowerCase(),
    files_generated: Object.keys(files).length,
    includes_mcp: body.include_mcp !== false,
    includes_skill: body.include_skill !== false,
    github_pr_url,
    // Return files inline if no GitHub delivery
    files: github_pr_url ? undefined : files,
  };
}

function collectFiles(root: string, dir: string, out: Record<string, string>) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      collectFiles(root, fullPath, out);
    } else {
      const relPath = path.relative(root, fullPath);
      out[relPath] = fs.readFileSync(fullPath, "utf-8");
    }
  }
}

async function deliverViaGitHub(
  files: Record<string, string>,
  repo: string,
  cliName: string,
  token: string
): Promise<string> {
  const [owner, repoName] = repo.split("/");
  const branch = `ppaas/${cliName}-${Date.now()}`;
  const baseUrl = `https://api.github.com/repos/${owner}/${repoName}`;

  const headers = {
    Authorization: `Bearer ${token}`,
    "Content-Type": "application/json",
    Accept: "application/vnd.github+json",
  };

  // Get default branch SHA
  const refResp = await fetch(`${baseUrl}/git/ref/heads/main`, { headers });
  const ref = await refResp.json();
  const sha = ref.object.sha;

  // Create branch
  await fetch(`${baseUrl}/git/refs`, {
    method: "POST",
    headers,
    body: JSON.stringify({ ref: `refs/heads/${branch}`, sha }),
  });

  // Push files
  for (const [filePath, content] of Object.entries(files)) {
    await fetch(`${baseUrl}/contents/cli/${cliName}/${filePath}`, {
      method: "PUT",
      headers,
      body: JSON.stringify({
        message: `feat: add ${cliName} CLI generated by PPaaS`,
        content: Buffer.from(content).toString("base64"),
        branch,
      }),
    });
  }

  // Create PR
  const prResp = await fetch(`${baseUrl}/pulls`, {
    method: "POST",
    headers,
    body: JSON.stringify({
      title: `feat: ${cliName} CLI + MCP server (PPaaS delivery)`,
      head: branch,
      base: "main",
      body: `Generated by [PPaaS](https://ppaas.printingpress.dev) for the **${cliName}** API.\n\n- Go CLI with all API endpoints as commands\n- MCP server for AI tool integration\n- Claude Code skill file`,
    }),
  });

  const pr = await prResp.json();
  return pr.html_url;
}

function buildCheckoutUrl(body: GenerateRequest): string {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "https://ppaas.printingpress.dev";
  const params = new URLSearchParams({
    api_url: body.api_url,
    api_name: body.api_name,
  });
  return `${baseUrl}/checkout?${params}`;
}
